POST http://localhost:8080/events
content-type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImphdGFsQGdtYWlsLmNvbSIsImV4cCI6MTczODI1NDE2MCwidXNlcklkIjoxfQ.ac3OH07KNjFF7MbcPwZqC2gc6uNMzoGwbkbR8N994Vw

{
    "name": "sleeping",
    "description": "Team meeting at office",
    "location": "Room 101",
    "date_time": "2025-01-27T15:04:05Z"
}