DELETE http://localhost:8080/events/1/unregister
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImphdGFsQGdtYWlsLmNvbSIsImV4cCI6MTczODI1NDE2MCwidXNlcklkIjoxfQ.ac3OH07KNjFF7MbcPwZqC2gc6uNMzoGwbkbR8N994Vw
